---
- name: Show Specific Ansible Fact
  hosts: servers
  gather_facts: true
  become: True
  become_user: root

  tasks:
    - name: Display Operating System
      debug:
        var: ansible_facts['distribution']
